export { default as Deck } from './Deck.svelte';
export { default as Slide } from './Slide.svelte';
export { default as Step } from './Step.svelte';
export { default as Steps } from './Steps.svelte';
export { default as Notes } from './Notes.svelte';
export { default as Canvas } from './Canvas.svelte';
export { layoutPresets, getPresetById } from './layoutPresets.js';
export type { LayoutPreset, RoleLayout } from './layoutPresets.js';
export { getDeckContext } from './context.js';
export { getSlideContext } from './slideContext.js';
export type { DeckContext } from './context.js';
export type { SlideContext } from './slideContext.js';
export type { TransitionPreset, Direction } from './transitions.js';
export { THEME_NAMES } from './themes/index.js';
export type { ThemeName } from './themes/index.js';
export { default as Text } from './components/Text.svelte';
export { default as Image } from './components/Image.svelte';
export { default as Code } from './components/Code.svelte';
export { default as List } from './components/List.svelte';
export { default as Background } from './components/Background.svelte';
export { default as Group } from './Group.svelte';
export type { DrawingState } from './drawing/drawingState.svelte.js';
export type { Stroke, Point, DrawingTool } from './drawing/types.js';
